/**
 * Copyright (C), 2026-02-05
 * @author ZestBox
 * @date 2026/02/05
 * @version 1.0
 * @description: 通用常量
 */

export class CommonConstants {
  /**
   * 包名
   */
  static readonly BUNDLE_NAME: string = "cn.zestbox.codeFlash";
  /**
   * 安全区避让高度
   */
  static readonly AVOID_RECT_HEIGHT_TOP: string = "topRectHeight";
  static readonly AVOID_RECT_HEIGHT_BOTTOM: string = "bottomRectHeight";
  /**
   * 页面
   */
  static readonly PAGE_INFOS: string = "pagesInfos";
  /**
   * 百分百
   */
  static readonly FULL_WIN: string = "100%";
  /**
   * 标题FREE高度
   */
  static readonly TITLE_BAR_HEIGHT_FREE: number = 138;
  /**
   * Tab标签蒙版高度
   */
  static readonly TAB_MASK_HEIGHT: number = 80;
}
