/**
 * Copyright (C), 2026-02-05
 * @author ZestBox
 * @date 2026/02/05
 * @version 1.0
 * @description: 路由器url常量
 */

const TAG: string = '[RouterUrlConstants]';

export class RouterUrlConstants {
  /**
   * 赞助
   */
  static readonly SPONSORSHIP: string = 'sponsorship';

  /**
   * 使用说明
   */
  static readonly USER_GUIDE: string = 'user_guide';

  /**
   * 常见问题
   */
  static readonly FAQ: string = 'faq';

}